export const MERGE = '@@resolve/MERGE'
export const SEND_COMMAND = '@@resolve/SEND_COMMAND'
export const SUBSCRIBE = '@@resolve/SUBSCRIBE'
export const UNSUBSCRIBE = '@@resolve/UNSUBSCRIBE'
export const SUBSCRIBE_READMODEL = '@@resolve/SUBSCRIBE_READMODEL'
export const UNSUBSCRIBE_READMODEL = '@@resolve/UNSUBSCRIBE_READMODEL'
export const PROVIDE_VIEW_MODELS = '@@resolve/PROVIDE_VIEW_MODELS'
export const DISCONNECT = '@@resolve/DISCONNECT'
