export const MERGE = '@@resolve/MERGE'
export const SEND_COMMAND = '@@resolve/SEND_COMMAND'
export const SUBSCRIBE_VIEWMODEL = '@@resolve/SUBSCRIBE_VIEWMODEL'
export const UNSUBSCRIBE_VIEWMODEL = '@@resolve/UNSUBSCRIBE_VIEWMODEL'
export const SUBSCRIBE_READMODEL = '@@resolve/SUBSCRIBE_READMODEL'
export const UNSUBSCRIBE_READMODEL = '@@resolve/UNSUBSCRIBE_READMODEL'
export const PROVIDE_VIEW_MODELS = '@@resolve/PROVIDE_VIEW_MODELS'
export const READMODEL_SUBSCRIPTION_DIFF =
  '@@resolve/READMODEL_SUBSCRIPTION_DIFF'
export const READMODEL_LOAD_INITIAL_STATE =
  '@@resolve/READMODEL_LOAD_INITIAL_STATE'
export const READMODEL_DROP_STATE = '@@resolve/READMODEL_DROP_STATE'
export const DISCONNECT = '@@resolve/DISCONNECT'
export const HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'
