export const SEND_COMMAND_REQUEST = '@@resolve/SEND_COMMAND_REQUEST'
export const SEND_COMMAND_SUCCESS = '@@resolve/SEND_COMMAND_SUCCESS'
export const SEND_COMMAND_FAILURE = '@@resolve/SEND_COMMAND_FAILURE'

//

export const DISPATCH_TOPIC_MESSAGE = '@@resolve/DISPATCH_TOPIC_MESSAGE'

//

export const CONNECT_VIEWMODEL = '@@resolve/CONNECT_VIEWMODEL'
export const DISCONNECT_VIEWMODEL = '@@resolve/DISCONNECT_VIEWMODEL'

export const QUERY_VIEWMODEL_REQUEST = '@@resolve/QUERY_VIEWMODEL_REQUEST'
export const QUERY_VIEWMODEL_SUCCESS = '@@resolve/QUERY_VIEWMODEL_SUCCESS'
export const QUERY_VIEWMODEL_FAILURE = '@@resolve/QUERY_VIEWMODEL_FAILURE'
export const VIEWMODEL_STATE_UPDATE = '@@resolve/VIEWMODEL_STATE_UPDATE'
export const VIEWMODEL_EVENT_RECEIVED = '@@resolve/VIEWMODEL_EVENT_RECEIVED'

export const DROP_VIEWMODEL_STATE = '@@resolve/DROP_VIEWMODEL_STATE'

//

export const CONNECT_READMODEL = '@@resolve/CONNECT_READMODEL'
export const DISCONNECT_READMODEL = '@@resolve/DISCONNECT_READMODEL'

export const QUERY_READMODEL_REQUEST = '@@resolve/QUERY_READMODEL_REQUEST'
export const QUERY_READMODEL_SUCCESS = '@@resolve/QUERY_READMODEL_SUCCESS'
export const QUERY_READMODEL_FAILURE = '@@resolve/QUERY_READMODEL_FAILURE'

export const DROP_READMODEL_STATE = '@@resolve/DROP_READMODEL_STATE'

//

export const HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'

//

export const UPDATE_JWT = '@@resolve/UPDATE_JWT'
export const LOGOUT = '@@resolve/LOGOUT'

//

export const AUTH_REQUEST = '@@resolve/AUTH_REQUEST'
export const AUTH_SUCCESS = '@@resolve/AUTH_SUCCESS'
export const AUTH_FAILURE = '@@resolve/AUTH_FAILURE'
