export const SEND_COMMAND_REQUEST = '@@resolve/SEND_COMMAND_REQUEST'
export const SEND_COMMAND_SUCCESS = '@@resolve/SEND_COMMAND_SUCCESS'
export const SEND_COMMAND_FAILURE = '@@resolve/SEND_COMMAND_FAILURE'

//

export const DISPATCH_TOPIC_MESSAGE = '@@resolve/DISPATCH_TOPIC_MESSAGE'

//

export const SUBSCRIBE_TOPIC_REQUEST = '@@resolve/SUBSCRIBE_TOPIC_REQUEST'
export const SUBSCRIBE_TOPIC_SUCCESS = '@@resolve/SUBSCRIBE_TOPIC_SUCCESS'
export const SUBSCRIBE_TOPIC_FAILURE = '@@resolve/SUBSCRIBE_TOPIC_FAILURE'

export const UNSUBSCRIBE_TOPIC_REQUEST = '@@resolve/UNSUBSCRIBE_TOPIC_REQUEST'
export const UNSUBSCRIBE_TOPIC_SUCCESS = '@@resolve/UNSUBSCRIBE_TOPIC_SUCCESS'
export const UNSUBSCRIBE_TOPIC_FAILURE = '@@resolve/UNSUBSCRIBE_TOPIC_FAILURE'

//

export const CONNECT_VIEWMODEL = '@@resolve/CONNECT_VIEWMODEL'
export const DISCONNECT_VIEWMODEL = '@@resolve/DISCONNECT_VIEWMODEL'

export const LOAD_VIEWMODEL_STATE_REQUEST =
  '@@resolve/LOAD_VIEWMODEL_STATE_REQUEST'
export const LOAD_VIEWMODEL_STATE_SUCCESS =
  '@@resolve/LOAD_VIEWMODEL_STATE_SUCCESS'
export const LOAD_VIEWMODEL_STATE_FAILURE =
  '@@resolve/LOAD_VIEWMODEL_STATE_FAILURE'

export const DROP_VIEWMODEL_STATE = '@@resolve/DROP_VIEWMODEL_STATE'

//

export const CONNECT_READMODEL = '@@resolve/CONNECT_READMODEL'
export const DISCONNECT_READMODEL = '@@resolve/DISCONNECT_READMODEL'

export const LOAD_READMODEL_STATE_REQUEST =
  '@@resolve/LOAD_READMODEL_STATE_REQUEST'
export const LOAD_READMODEL_STATE_SUCCESS =
  '@@resolve/LOAD_READMODEL_STATE_SUCCESS'
export const LOAD_READMODEL_STATE_FAILURE =
  '@@resolve/LOAD_READMODEL_STATE_FAILURE'

export const DROP_READMODEL_STATE = '@@resolve/DROP_READMODEL_STATE'

//

export const HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'

//

export const UPDATE_JWT = '@@resolve/UPDATE_JWT'
export const LOGOUT = '@@resolve/LOGOUT'

//

export const AUTH_REQUEST = '@@resolve/AUTH_REQUEST'
export const AUTH_SUCCESS = '@@resolve/AUTH_SUCCESS'
export const AUTH_FAILURE = '@@resolve/AUTH_FAILURE'
