export const REFRESH_ID_UPDATED = 'REFRESH_ID_UPDATED'

export const USER_LOGOUT = 'USER_LOGOUT'

export const OPTIMISTIC_STORY_UPVOTED = 'OPTIMISTIC_STORY_UPVOTED'
export const OPTIMISTIC_STORY_UNVOTED = 'OPTIMISTIC_STORY_UNVOTED'

export const OPTIMISTIC_COMMENTS_LOADED = 'OPTIMISTIC_COMMENTS_LOADED'
export const OPTIMISTIC_COMMENT_CREATED = 'OPTIMISTIC_COMMENT_CREATED'
export const OPTIMISTIC_COMMENT_UPDATED = 'OPTIMISTIC_COMMENT_UPDATED'
export const OPTIMISTIC_COMMENT_REMOVED = 'OPTIMISTIC_COMMENT_REMOVED'
