language: node_js
node_js:
  - "6"
  - "8"
before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run test:e2e
