kind: pipeline
type: docker
name: build

steps:
  - name: publish-nightly
    when:
      event: push
    image: reimagined/resolve-docker
    pull: always
    environment:
      NPM_REGISTRY:
        from_secret: npm_registry
      NPM_TOKEN:
        from_secret: npm_token
      RESOLVE_ALLOW_PARALLEL_BUILDS: false
    commands:
      - yarn
      - VERSION=$(/scripts/prepare_downstream)
      - /scripts/npm_patch_rc
      - npx oao all "/scripts/package_json patch-dependencies '(?!resolve-cloud-common$)(resolve-.*$)' $VERSION && /scripts/npm_publish $VERSION nightly"

trigger:
  branch:
    - dev
---
kind: pipeline
type: docker
name: build-redux

steps:
  - name: publish-nightly
    when:
      event: push
    image: reimagined/resolve-docker
    pull: always
    environment:
      NPM_REGISTRY:
        from_secret: npm_registry
      NPM_TOKEN:
        from_secret: npm_token
      RESOLVE_ALLOW_PARALLEL_BUILDS: false
    commands:
      - yarn
      - VERSION=$(/scripts/prepare_downstream)
      - /scripts/npm_patch_rc
      - npx oao all "/scripts/package_json patch-dependencies '(?!resolve-cloud-common$)(resolve-.*$)' $VERSION && /scripts/npm_publish $VERSION redux-dev"

trigger:
  branch:
    - feature/customizable-redux
