export const USER_REGISTERED = 'USER_REGISTERED'
export const USER_LIKED = 'USER_LIKED'
export const COUNTER_INCREASED = 'COUNTER_INCREASED'
export const COUNTER_DECREASED = 'COUNTER_DECREASED'
export const TEST_SCENARIO_EXECUTED = 'TEST_SCENARIO_EXECUTED'
export const TEST_SCENARIO_RETRY_ON_ERROR_UNBLOCKED =
  'TEST_SCENARIO_RETRY_ON_ERROR_UNBLOCKED'
export const TEST_SCENARIO_RETRY_ON_ERROR_COMPLETED =
  'TEST_SCENARIO_RETRY_ON_ERROR_COMPLETED'
export const MONITORING_FAILED_HANDLER = 'MONITORING_FAILED_HANDLER'
export const MONITORING_VIEW_MODEL_FAILED = 'MONITORING_VIEW_MODEL_FAILED'
