import optimisticShoppingListsMiddleware from './optimistic_shopping_lists_middleware'
import optimisticSharingsMiddleware from './optimistic_sharings_middleware'

export default [optimisticShoppingListsMiddleware, optimisticSharingsMiddleware]
