import optimistic_shopping_lists_middleware from './optimistic_shopping_lists_middleware'
import optimisticSharingsMiddleware from './optimistic_sharings_middleware'

export default [optimistic_shopping_lists_middleware, optimisticSharingsMiddleware]
