export const SHOPPING_LIST_CREATED = 'SHOPPING_LIST_CREATED'

export const SHOPPING_LIST_RENAMED = 'SHOPPING_LIST_RENAMED'

export const SHOPPING_LIST_REMOVED = 'SHOPPING_LIST_REMOVED'

export const SHOPPING_ITEM_CREATED = 'SHOPPING_ITEM_CREATED'

export const SHOPPING_ITEM_TOGGLED = 'SHOPPING_ITEM_TOGGLED'

export const SHOPPING_ITEM_REMOVED = 'SHOPPING_ITEM_REMOVED'

export const SHOPPING_LIST_SHARED = 'SHOPPING_LIST_SHARED'

export const SHOPPING_LIST_UNSHARED = 'SHOPPING_LIST_UNSHARED'

export const USER_CREATED = 'USER_CREATED'

export const USER_NAME_UPDATED = 'USER_NAME_UPDATED'
