export const OPTIMISTIC_SHARE_SHOPPING_LIST = 'OPTIMISTIC_SHARE_SHOPPING_LIST'

export const OPTIMISTIC_UNSHARE_SHOPPING_LIST =
  'OPTIMISTIC_UNSHARE_SHOPPING_LIST'

export const OPTIMISTIC_CREATE_SHOPPING_LIST = 'OPTIMISTIC_CREATE_SHOPPING_LIST'
