export const OPTIMISTIC_SHARINGS_SYNC = 'OPTIMISTIC_SHARINGS_SYNC'

export const OPTIMISTIC_SHARINGS_SHOPPING_LIST_SHARE =
  'OPTIMISTIC_SHARINGS_SHOPPING_LIST_SHARE'

export const OPTIMISTIC_SHARINGS_SHOPPING_LIST_UNSHARE =
  'OPTIMISTIC_SHARINGS_SHOPPING_LIST_UNSHARE'

//

export const OPTIMISTIC_SHOPPING_LIST_SYNC = 'OPTIMISTIC_SHOPPING_LIST_SYNC'

export const OPTIMISTIC_SHOPPING_LIST_CREATE = 'OPTIMISTIC_SHOPPING_LIST_CREATE'

export const OPTIMISTIC_SHOPPING_LIST_REMOVE = 'OPTIMISTIC_SHOPPING_LIST_REMOVE'
