export const RESOLVE_SAGA_PREFIX = `_RESOLVE_SAGA_`
export const RESOLVE_SCHEDULER_SAGA_PREFIX = `_RESOLVE_SCHEDULER_SAGA_`
export const RESOLVE_SCHEDULER_TABLE_PREFIX = `_RESOLVE_SCHEDULER_TABLE_`
export const RESOLVE_SCHEDULER_AGGREGATE_PREFIX = `_RESOLVE_SCHEDULER_AGGREGATE_`
