export const MY_AGGREGATE_CREATED = 'MY_AGGREGATE_CREATED'
export const MY_AGGREGATE_ITEM_ADDED = 'MY_AGGREGATE_ITEM_ADDED'
export const MY_AGGREGATE_ITEM_REMOVED = 'MY_AGGREGATE_ITEM_REMOVED'
export const MY_AGGREGATE_DELETED = 'MY_AGGREGATE_DELETED'
