export const MY_AGGREGATE_CREATED = 'ENTITY_CREATED'
export const MY_AGGREGATE_ITEM_ADDED = 'ENTITY_ITEM_ADDED'
export const MY_AGGREGATE_ITEM_REMOVED = 'ENTITY_ITEM_REMOVED'
export const MY_AGGREGATE_DELETED = 'ENTITY_DELETED'
