name: npm publish
description: publishes packages to specified repository
inputs:
  npm_registry:
    description: NPM registry to publish to
    required: true
  npm_token:
    description: NPM registry authentication token
    required: true
  release_type:
    description: release type specifier (specify 'release' to use version as is)
    required: true
  version:
    description: packages version (specify 'current' to use version from package.json)
    required: true
  tag:
    description: packages tag
    required: false
  unpublish:
    description: automatically unpublish packages on post hook
    required: false
    default: 'false'

outputs:
  version:
    description: deployed application id
  app_name:
    description: deployed application name
  app_url:
    description: deployed application url
  app_runtime:
    description: deployed applicaiton runtime version

runs:
  using: 'node12'
  main: 'index.js'
  post: 'cleanup.js'
