version: '3'
services:
  testcafe:
    build:
      context: .
      dockerfile: testcafe.dockerfile
    command:
      - firefox
      - /tests
    links:
      - todo
    depends_on:
      - todo
    environment:
      - HOST=todo
  todo:
    build: .
