#!/usr/bin/env bash

SHOULD_EXIT=0

if [ -z ${NPM_REGISTRY} ]; then
    echo 'NPM_REGISTRY env var not set';
    SHOULD_EXIT=1
fi

if [ -z ${NPM_TOKEN} ]; then
    echo 'NPM_TOKEN env var not set';
    SHOULD_EXIT=1
fi

if [ ${SHOULD_EXIT} != 0 ]; then
    exit 1;
fi

echo NPM_REGISTRY=${NPM_REGISTRY}

echo Patching ~/.npmrc
echo "//${NPM_REGISTRY}/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
echo "//${NPM_REGISTRY}/:always-auth=true" >> ~/.npmrc
echo "registry=http://${NPM_REGISTRY}" >> ~/.npmrc

echo Patching ~/.yarnrc
echo "registry \"http://${NPM_REGISTRY}\"" >> ~/.yarnrc
