import optimisticShoppingListsMiddleware from './optimisticShoppingListsMiddleware'
import optimisticSharingsMiddleware from './optimisticSharingsMiddleware'

export default [optimisticShoppingListsMiddleware, optimisticSharingsMiddleware]
