export const ENTITY_CREATED = 'ENTITY_CREATED'

export const ENTITY_ITEM_ADDED = 'ENTITY_ITEM_ADDED'

export const ENTITY_ITEM_REMOVED = 'ENTITY_ITEM_REMOVED'

export const ENTITY_DELETED = 'ENTITY_DELETED'
