export const CLIENT_TO_SERVER_TOPICS = {
  DECLARE_EVENT_TYPES_TOPIC: 'DECLARE_EVENT_TYPES_TOPIC',
  EVENT_TOPIC: 'EVENT-TOPIC',
  RESET_LISTENER_TOPIC: 'RESET-LISTENER-TOPIC',
  PAUSE_LISTENER_TOPIC: 'PAUSE-LISTENER-TOPIC',
  RESUME_LISTENER_TOPIC: 'RESUME-LISTENER-TOPIC',
  ACKNOWLEDGE_BATCH_TOPIC: 'ACKNOWLEDGE-BATCH-TOPIC',
  INFORMATION_TOPIC: 'INFORMATION-TOPIC',
  PROPERTIES_TOPIC: 'PROPERTIES-TOPIC'
}

export const SERVER_TO_CLIENT_TOPICS = {
  INFORMATION_TOPIC: '__RESOLVE_INFORMATION_TOPIC__',
  RESET_LISTENER_ACKNOWLEDGE_TOPIC:
    '__RESOLVE_RESET_LISTENER_ACKNOWLEDGE_TOPIC__',
  PROPERTIES_TOPIC: '__RESOLVE_PROPERTIES_TOPIC__'
}

export const RESOLVE_SIDE_EFFECTS_START_TIMESTAMP =
  'RESOLVE_SIDE_EFFECTS_START_TIMESTAMP'

export const LOCK_PROMISE_BASE_NAME = 'LOCK-PROMISE'

export const READ_MODEL_STATUS = {
  running: 'running',
  paused: 'paused',
  pausedOnError: 'pausedOnError'
}

export const BATCH_STEP_RESULT = {
  CONTINUE: true,
  STOP: false
}
