name: dev (push)

on:
  push:
    branches:
      - dev

jobs:
  e2e-mac:
    runs-on: [self-hosted, macOS, X64, resolve-mac-mini]
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test:e2e (mac:safari)
        env:
          RESOLVE_E2E_TESTS_BROWSER: safari
          RESOLVE_E2E_TESTS_HEADLESS_MODE: false
          DEBUG: resolve:scripts*
          DEBUG_LEVEL: debug
        run: yarn test:e2e

  publish-dev:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Install & Build
        run: |
          echo "installing packages and building the repository"
          yarn install --frozen-lockfile

      - name: Publish to private repository
        uses: reimagined/github-actions/publish@v1
        with:
          registry: github
          token: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
          version: auto
          build: ${{ github.sha }}
          tag: dev
          unpublish: false
          github_target_repository: resolve-js/resolve

